spring.datasource.url=jdbc:mysql://localhost:3306/cartify
spring.datasource.username=root
spring.datasource.password=Rahul@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


cloudinary.cloud_name=dxt1ls10c
cloudinary.api_key=938284857855283
cloudinary.api_secret=ZS2JTEJclXNj7lwN4wLhXx3jbt0
